using Amazon;
using Amazon.Runtime;
using Amazon.SQS;
using Amazon.SQS.Model;
using Frends.AmazonSQS.Receive.Definitions;
using Frends.AmazonSQS.Receive.Enums;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using System.Threading.Tasks;

namespace Frends.AmazonSQS.Receive;

/// <summary>
/// Amazon S3 Task.
/// </summary>
public class AmazonSQS
{
    /// <summary>
    /// Frends Task for receiving messages from AmazonSQS.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AmazonSQS.Receive)
    /// </summary>
    /// <param name="connection">Connection parameters.</param>
    /// <param name="input">Input parameters.</param>
    /// <param name="options">Optional parameters.</param>
    /// <param name="cancellationToken">Token generated by frends to stop this Task.</param>
    /// <returns>Object { long ContentLength, Object HttpStatusCode StatusCode, List { Object Message } Messages, Object ResponseMetadata ResponseMetadata }</returns>
    public static async Task<Result> Receive([PropertyTab] Connection connection, [PropertyTab] Input input, [PropertyTab] Options options, CancellationToken cancellationToken)
    {
        using var sqsClient = GetAmazonSQSClient(connection.UseDefaultCredentials, ConstructAWSCredentials(connection), connection.Region);

        var request = new ReceiveMessageRequest
        {
            AttributeNames = new List<string>() { "All" },
            MaxNumberOfMessages = input.MaxNumberOfMessages,
            QueueUrl = input.QueueUrl,
            VisibilityTimeout = options.VisibilityTimeout,
            WaitTimeSeconds = options.WaitTimeSeconds
        };

        // https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SQS/TReceiveMessageResponse.html
        var response = await sqsClient.ReceiveMessageAsync(request, cancellationToken);

        // Remove messages after receiving?
        if (response.Messages.Count > 0 && options.DeleteMessageAfterReceiving)
        {
            foreach (var message in response.Messages)
            {
                cancellationToken.ThrowIfCancellationRequested();
                var deleteMessageRequest = new DeleteMessageRequest()
                {
                    QueueUrl = input.QueueUrl,
                    ReceiptHandle = message.ReceiptHandle
                };
                // https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SQS/TDeleteMessageResponse.html
                await sqsClient.DeleteMessageAsync(deleteMessageRequest);
            }
        }

        return new Result(response);
    }

    internal static AmazonSQSClient GetAmazonSQSClient(bool useDefaultCredentials, AWSCredentials awsCredentials, Region region)
    {
        // App.config or EC2 instance credentials?
        if (useDefaultCredentials)
        {
            if (region == Region.Undefined)
                return new AmazonSQSClient();
            else
                return new AmazonSQSClient(RegionSelection(region));
        }

        if (region == Region.Undefined)
            return new AmazonSQSClient(awsCredentials);
        else
            return new AmazonSQSClient(awsCredentials, RegionSelection(region));
    }

    internal static dynamic ConstructAWSCredentials(Connection connection)
    {
        if (connection.UseDefaultCredentials)
            return null;

        return connection.CredentialsType switch
        {
            AWSCredentialsType.BasicAWSCredentials => new BasicAWSCredentials(connection.AccessKey, connection.SecretKey),
            AWSCredentialsType.AnonymousAWSCredentials => new AnonymousAWSCredentials(),
            AWSCredentialsType.EnvironmentAWSCredentials => new EnvironmentVariablesAWSCredentials(),
            AWSCredentialsType.SessionAWSCredentials => new SessionAWSCredentials(connection.AccessKey, connection.SecretKey, connection.SessionToken),
            _ => throw new InvalidEnumArgumentException("Unknown credentials type."),
        };
    }

    /// <summary>
    /// Excluded from code coverage because only single region can be used with test system.
    /// </summary>
    [ExcludeFromCodeCoverage]
    private static RegionEndpoint RegionSelection(Region region)
    {
        return region switch
        {
            Region.EuNorth1 => RegionEndpoint.EUNorth1,
            Region.EuWest1 => RegionEndpoint.EUWest1,
            Region.EuWest2 => RegionEndpoint.EUWest2,
            Region.EuWest3 => RegionEndpoint.EUWest3,
            Region.EuCentral1 => RegionEndpoint.EUCentral1,
            Region.ApSoutheast1 => RegionEndpoint.APSoutheast1,
            Region.ApSoutheast2 => RegionEndpoint.APSoutheast2,
            Region.ApNortheast1 => RegionEndpoint.APNortheast1,
            Region.ApNortheast2 => RegionEndpoint.APNortheast2,
            Region.ApSouth1 => RegionEndpoint.APSouth1,
            Region.CaCentral1 => RegionEndpoint.CACentral1,
            Region.CnNorth1 => RegionEndpoint.CNNorth1,
            Region.CnNorthWest1 => RegionEndpoint.CNNorthWest1,
            Region.SaEast1 => RegionEndpoint.SAEast1,
            Region.UsEast1 => RegionEndpoint.USEast1,
            Region.UsEast2 => RegionEndpoint.USEast2,
            Region.UsWest1 => RegionEndpoint.USWest1,
            Region.UsWest2 => RegionEndpoint.USWest2,
            _ => RegionEndpoint.EUNorth1,
        };
    }
}